- label: "PR submitted by:"
  message: "$payload.pull_request.user.login"
  color: "blue"
- label: "PR Size"
  message: "Large: $additions"
  color: "red"
  when: "$additions > 250"
- label: "PR Size"
  message: "Medium: $additions"
  color: "orange"
  when: "$additions > 99 && $additions < 251"
- label: "PR Size"
  message: "Ok: $additions"
  color: "green"
  when: "$additions < 100"
- imageUrl: "https://gitlab.cern.ch/rest-for-physics/restG4/badges/$branchName/pipeline.svg"
  url: "https://gitlab.cern.ch/rest-for-physics/restG4/-/commits/$branchName"
- imageUrl: "https://gitlab.cern.ch/rest-for-physics/geant4lib/badges/$branchName/pipeline.svg"
  url: "https://gitlab.cern.ch/rest-for-physics/geant4lib/-/commits/$branchName"
- imageUrl: "https://gitlab.cern.ch/rest-for-physics/framework/badges/$branchName/pipeline.svg"
  url: "https://gitlab.cern.ch/rest-for-physics/framework/-/commits/$branchName"
- imageUrl: "https://github.com/rest-for-physics/restG4/actions/workflows/validation.yml/badge.svg?branch=$branchName"
  url: "  https://github.com/rest-for-physics/restG4/commits/$branchName"
